name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Build Database project
        run: |
          msbuild.exe sqlproject/sqlproject.sln /p:Configuration=Release
          
      - name: Create Artifacts Directory
        run: |
          New-Item -ItemType Directory -Force -Path (Join-Path ${{ github.workspace }} 'artifacts')
          
      - name: Copy Artifacts
        run: |
          $sourcePath = "${{ github.workspace }}\sqlproject\sqlproject\bin\Release"
          $destinationPath = (Join-Path ${{ github.workspace }} 'artifacts')
          Copy-Item -Path "$sourcePath\*" -Destination $destinationPath -Recurse -Force
          
      - name: List Artifacts Content
        run: |
          Get-ChildItem -Path (Join-Path ${{ github.workspace }} 'artifacts') -Recurse
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dacpaclogs
          path: ${{ github.workspace }}\artifacts\
          
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
      # Artifact name
         name: Dacpaclogs
      # Destination path
         path: ${{ github.workspace }}/downloaded_artifacts
         
      - name: Install SQLPackage
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2108816" -OutFile "sqlpackage.zip" -ErrorAction Continue
          Expand-Archive -Path "sqlpackage.zip" -DestinationPath ".\sqlpackage"
