#This is sql CI
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        
      - name: Build Database project
        run: |
          msbuild.exe sqlproject/Database2.sln /p:Configuration=Release
          
      - name: Create Artifacts Directory
        run: |
          New-Item -ItemType Directory -Force -Path (Join-Path ${{ github.workspace }} 'artifacts')
          
      - name: Copy Artifacts
        run: |
          $sourcePath = "${{ github.workspace }}\sqlproject\Database2\bin\Release"
          $destinationPath = (Join-Path ${{ github.workspace }} 'artifacts')
          Copy-Item -Path "$sourcePath\*" -Destination $destinationPath -Recurse -Force
          
      - name: List Artifacts Content
        run: |
          Get-ChildItem -Path (Join-Path ${{ github.workspace }} 'artifacts') -Recurse
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dacpaclogs
          path: ${{ github.workspace }}\artifacts\
          
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
      # Artifact name
         name: Dacpaclogs
      # Destination path
         path: ${{ github.workspace }}/downloaded_artifacts
         
      #- name: Install SQLPackage
      #  run: |
      #    Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      #    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      #    Invoke-WebRequest -Uri "https://download.microsoft.com/download/4/1/A/41AD9910-C3A5-4798-B418-EF5DDC9DBA59/ENU/ssdt-setup-ENU.exe" -OutFile "ssdt-setup.exe"
      #    Start-Process -FilePath ".\ssdt-setup.exe" -ArgumentList "/Quiet /NoRestart /Layout .\sqlpackage" -Wait
      #    Expand-Archive -Path ".\sqlpackage\payload\*
      #    \Microsoft.Data.Tools.Msbuild\lib\net40\*.zip" -DestinationPath ".\sqlpackage\unzipped" -Force

      - name: Deploy Database
        run: |
          $serverName = "sql1987.database.windows.net"
          $userName = "testaccount"
          $password = "admin@1234"
          $dbName = "newdb890"
          $dacpacPath = "${{ github.workspace }}\downloaded_artifacts\sqlproject.dacpac"
