#This is sql CI
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x86
          vswhere_path: 'C:\Program Files (x86)\microsoft visual studio\installer\vswhere.exe'
        
      - name: Build Database project
        run: |
          msbuild.exe sqlproject/Database2.sln /p:Configuration=Release
          
      - name: Create Artifacts Directory
        run: |
          New-Item -ItemType Directory -Force -Path (Join-Path ${{ github.workspace }} 'artifacts')
          
      - name: Copy Artifacts
        run: |
          $sourcePath = "${{ github.workspace }}\sqlproject\Database2\bin\Release"
          $destinationPath = (Join-Path ${{ github.workspace }} 'artifacts')
          Copy-Item -Path "$sourcePath\*" -Destination $destinationPath -Recurse -Force
          
      - name: List Artifacts Content
        run: |
          Get-ChildItem -Path (Join-Path ${{ github.workspace }} 'artifacts') -Recurse
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Dacpaclogs
          path: ${{ github.workspace }}\artifacts\
          
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
      # Artifact name
         name: Dacpaclogs
      # Destination path
         path: ${{ github.workspace }}/downloaded_artifacts
         
      - name: Install SQLPackage
        run: |
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2128310" -OutFile "C:\Windows\Temp\DacFramework.msi"
          Start-Process "msiexec" -ArgumentList "/I C:\Windows\Temp\DacFramework.msi /quiet /norestart" -Wait

      - name: Deploy Database
        run: |
          $serverName = "sql1987.database.windows.net"
          $userName = "testaccount"
          $password = "admin@1234"
          $dbName = "benz"
          $dacpacPath = "${{ github.workspace }}\downloaded_artifacts\Database2.dacpac"

          & "C:/Program Files/Microsoft SQL Server/160/DAC/bin/sqlpackage.exe" /Action:Publish /SourceFile:$dacpacPath /TargetServerName:$serverName /TargetDatabaseName:$dbName /TargetUser:$userName /TargetPassword:$password /p:BlockWhenDriftDetected=False
